# server block represents one website or one application
server {
    #NGINX to listen on port 80 for incoming HTTP requests
    listen 80;
    
    # Tells NGINX where your website files stored. In this case, it's set to /usr/share/nginx/html, which is the default document root for NGINX.
    root /usr/share/nginx/html
    #This tells NGINX which file to serve by default when the user opens a folder path.
    index index.html index.htm
    
    # Location block tells NGINX what to do for a particular URL path.
    location / {
        # This directive tells NGINX to try to serve the requested URI as a file. If it doesn't exist, it will try to serve it as a directory. If that also fails, it will return a 404 Not Found error.
        #$uri represents the requested URI, and $uri/ represents the same URI but treated as a directory.
        try_files $uri $uri/ =404;
    }
}